# Generated by Django 4.1.3 on 2022-11-21 18:32

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_flexpage_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='flexpage',
            name='sub_title_one',
            field=wagtail.fields.RichTextField(default='', verbose_name=' Sub title one'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flexpage',
            name='sub_title_two',
            field=wagtail.fields.RichTextField(default='momo', verbose_name=' Sub title two'),
            preserve_default=False,
        ),
    ]
