# Generated by Django 4.1.3 on 2022-11-21 19:17

from django.db import migrations
import streams.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_remove_flexpage_sub_title_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('full_richtext', streams.blocks.RichTextBlock())], blank=True, null=True, use_json_field=None),
        ),
    ]
