# Generated by Django 4.1.3 on 2022-11-21 19:24

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0006_alter_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('full_richtext', streams.blocks.RichTextBlock()), ('main_title', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
